services:
  shop-service:
    image: shop-service
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    networks:
      - shop-service
  
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    networks:
      - shop-service
    environment:
      POSTGRES_DB: "eStoreHub"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345890"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d eStoreHub",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  postgres-data:

networks:
  shop-service:
    driver: bridge
